api/urls.py
from . import views
from django.urls import path 

urlpatterns = [
    path('get_all_user/',views.get_all_user.as_view()),
]

server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include('api.urls')),
    path('',include('webapp.urls')),
]

webapp/urls.py
from . import views
from django.urls import path 

app_name = 'webapp'
urlpatterns = [
    path('',views.home, name='home'),
    path('login/',views.login, name='login'),
    path('logout/',views.logout, name='logout'),
    path('action/<str:id>',views.action, name='action'),
    path('registration/',views.registration, name='regis'),
]

api/models.py
from django.db import models
from datetime import datetime    
from django.utils import timezone

class refridgerator_display_system(models.Model):
    name = models.TextField(default="")
    id = models.TextField(primary_key=True)
    datetime_regis = models.DateTimeField(default=timezone.now())

class history(models.Model):
    ref_id = models.ForeignKey(refridgerator_display_system,on_delete=models.CASCADE)
    datetime = models.DateTimeField(default=timezone.now())

webapp/models.py
from django.db import models

# Create your models here.

api/views.py
from django.shortcuts import render
from django.contrib.auth.models import User

from rest_framework.views import APIView
from rest_framework.response import Response

from .models import refridgerator_display_system,history

class get_all_user(APIView):
    def get(self,request):
        try:
            get_id = self.request.query_params.get('id')
            thisID = refridgerator_display_system.objects.get(id=get_id)
        except:
            print("There is Invalid ID trying to access : "+str(get_id))
            return Response({"id": get_id,"OK": False})
        else:
            history.objects.create(ref_id=thisID)
            print("making History")
            return Response({"id": get_id,"OK": True})

webapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse ,HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth.models import User
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

from django.contrib.auth import authenticate

from django.contrib.auth.hashers import check_password

from api.models import refridgerator_display_system,history

def home(request):
    if request.user.is_authenticated:
        info = refridgerator_display_system.objects.all()
        return render(request, 'home.html',{'information':info})
    else:
        return render(request, 'login.html')

def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        auth_login(request, user)
        return HttpResponseRedirect(reverse('webapp:home'))
    else:
        return render(request, 'login.html',{'err': "Error, username or password is not correct"})

def logout(request):
    auth_logout(request)
    return render(request,'login.html',{'err': "Log Out Complete!"})

def registration(request):
    if request.POST['name'] and request.POST['id']:
        refridgerator_display_system.objects.create(id=request.POST['id'],name=request.POST['name'])
        return HttpResponseRedirect(reverse('webapp:home'))
    else:
        return HttpResponseRedirect(reverse('webapp:home'))


def action(request,id):
    if request.user.is_superuser:
        try:
            if(request.POST['save']):
                print("1111111")
                thisID = refridgerator_display_system.objects.get(id=id)
                thisID.name = request.POST['name']
                print("1111111")
                print(thisID)
                thisID.save()
        except:
            if(request.POST['delete']):
                refridgerator_display_system.objects.get(id=id).delete()
        return HttpResponseRedirect(reverse('webapp:home'))
    else:
        return HttpResponseRedirect(reverse('webapp:home'))

webapp/templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
	.ssp {font-family: 'Source Sans Pro', sans-serif}
	body {margin:0;}
	* {
	box-sizing: border-box;
	}

	fieldset {
  display: block;
  margin-left: 10px;
  margin-right: 2px;
  padding-top: 0.35em;
  padding-bottom: 0.625em;
  padding-left: 0.75em;
  padding-right: 0.75em;
  border: 2px groove (internal value);
  width:380px;
	font-size:18px;
	}
	.small {
	  width:300px;
	}
	.left {
	  float:left;
	  width:50%;
	}
	.right {
	  float:left;
	  width:50%;
	}
	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 16px 32px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
		margin-left: 10px;
	  margin-right: 2px;
	  -webkit-transition-duration: 0.4s; /* Safari */
	  transition-duration: 0.4s;
	  cursor: pointer;
	}
	.button1 {
	  background-color: white;
	  color: black;
	  border: 2px solid #000000;
		position: relative;
	}

	.button1:hover {
	  background-color: #000000;
	  color: white;
	}
	.rightmenu {
		font-family: 'Source Sans Pro', sans-serif; background-color: green;
	}
	.leftmenu {
		font-family: 'Source Sans Pro', sans-serif; background-color: grey;
	}
	ul {
	  list-style-type: none;
	  margin: 0;
	  padding: 0;
	  overflow: hidden;
	  background-color: black	;
	  position: fixed;
	  top: 0;
	  width: 100%;
	}

	li {
	  float: left;
	}

	li a {
	  display: block;
	  color: white;
	  text-align: center;
	  padding: 14px 16px;
	  text-decoration: none;
	}

	.rightmenu {
	  background-color: red;
	}
	</style>
</head>
	<body style= " background: url(https://www.setaswall.com/wp-content/uploads/2017/03/Artistic-4K-Wallpaper-3840x2160.jpg); background-size: cover">
	<ul>
		<li><img src="https://www.kmutnb.ac.th/getattachment/about/symbols/logo_kmutnb-(6).png.aspx?width=250&height=246" width="42" height="42"></li>
		<li><a class="ssp" style="color: white">ADMIN</a></li>
        <li style="float:right"><a class="ssp" class="rightmenu" href="{% url 'webapp:logout' %}">Logout</a></li>
        <li style="float:right"><a href="{% url 'webapp:home' %}" class="ssp" >{{ user.get_username }}</a></li>
	</ul>
	</br>
	</br>
			<fieldset>
			<legend><h3 class="ssp" style="color: white">Informations</h3></legend>
				<table border="1">
				<tr  class="ssp" style="color: white">
					<th>ID</th>
					<th>Name</th>
					<th>Registration Datetime</th>
				</tr>
						{% for data in information %}
							<div style="overflow-x:auto;"></div>
							<tr class="ssp" style="color: white">
								<form action="{% url 'webapp:action' data.id%}" method="post">
								{% csrf_token %}
								<td>{{data.id}}</td>
								<td><input type="text" name="name" placeholder={{data.name}} value={{data.name}}></td>
								<td><input type="text" name="datetime" placeholder={{data.datetime_regis}} value={{data.datetime_regis}}></td>

								<td><input type="submit" name="save" value="Save"></td>
								<td><input type="submit" name="delete" value="Delete"></td>
								</form>
							</tr>

							</div>
						</form>
						{% endfor %}
								<form action="{% url 'webapp:regis' %}" method="post">
								{% csrf_token %}
								<tr>
								<td><input type="text" name="id" placeholder="ID Card"></td>
								<td><input type="text" name="name" placeholder="Name"></td>
								<td></td>

								<td><input type="submit" value="Enter"></td>
								</tr>
								</form>
				</table>
			</fieldset>
			{{ err }}
			</br>
	</body>
</html>

webapp/templates/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
	/*
	font-family: 'Source Sans Pro', sans-serif;
	font-family: 'Questrial', sans-serif;
	font-family: 'Cinzel', serif;
	font-family: 'Bree Serif', serif;
	*/
	.ssp {font-family: 'Source Sans Pro', sans-serif;}
	body {margin:0;}
	* {
	box-sizing: border-box;
	}

	fieldset {
  display: block;
  margin-left: 10px;
  margin-right: 2px;
  padding-top: 0.35em;
  padding-bottom: 0.625em;
  padding-left: 0.75em;
  padding-right: 0.75em;
  border: 2px groove (internal value);
  width:300px;
	font-size:18px;
	}

	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 16px 32px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
		margin-left: 10px;
	  margin-right: 2px;
	  -webkit-transition-duration: 0.4s; /* Safari */
	  transition-duration: 0.4s;
	  cursor: pointer;
	}
	.button1 {
	  background-color: white;
	  color: black;
	  border: 2px solid #000000;
		position: relative;
	}

	.button1:hover {
	  background-color: #000000;
	  color: white;
	}

	ul {
	  list-style-type: none;
	  margin: 0;
	  padding: 0;
	  overflow: hidden;
	  background-color:none	;
	  position: fixed;
	  top: 0;
	  width: 100%;
	}

	li {
	  float: left;
	}

	li a {
	  display: block;
	  color: white;
	  text-align: center;
	  padding: 14px 16px;
	  text-decoration: none;
	}

	.rightmenu {
		font-family: 'Source Sans Pro', sans-serif; background-color: green;
	}
	</style>
</head>
	<body style= " background: url(https://www.setaswall.com/wp-content/uploads/2017/03/Artistic-4K-Wallpaper-3840x2160.jpg); background-size: cover">
	<ul>
		<li><img src="https://www.kmutnb.ac.th/getattachment/about/symbols/logo_kmutnb-(6).png.aspx?width=250&height=246" width="100" height="100"></li>
	  	<li><a class="ssp" style="font-size: 200%">Mechatronics Project</a></li>
	</ul>
		<br><br><pre class="ssp" style="color: white">                           King Mongkut's University of Technology North Bangkok</pre>
		<br><h2 class="ssp" style="color: white">{{ err }}</h2>
		<form action="{% url 'webapp:login' %}" method="post">
		<span class="ssp" style="color: white">
			{% csrf_token %}
		</span>
		<fieldset>
		 <legend><h2 class="ssp" style="color: white">Login</h2></legend>
			<span class="ssp" style="color: white">
				Username: <input type="text" name="username" placeholder="Username"><br><br>
				Password: <input type="password" name="password" placeholder="Password"><br><br>
			</span>
			<input class="ssp" type="submit" value="Sign In">
		</fieldset>
	</form>
	</body>
</html>